version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hexocean
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=Admin123
  api:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
             python manage.py migrate &&
             python manage.py setup &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/imageApi/ 
    ports:
      - "8000:8000"
    restart: on-failure
    links:
      - db
